### ISSUE TITLE
libsgx-urts v2.9 dependency

### ISSUE THREAD

**Issue by eddyashton** [intel/SGXDataCenterAttestationPrimitives#105]
In the 1.6 release, and the current master, the debian package for `libsgx-pce-logic` lists a dependency on `libsgx-urts` 2.8 (or higher):

https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/installer/linux/deb/libsgx-pce-logic/libsgx-pce-logic-1.0/debian/control

I believe this is incorrect, and the current code actually depends on 2.9. When trying to build with 1.6, and `libsgx-urts` 2.8, I got linking errors on `sgx_get_metadata` (which I believe was moved between packages?):

```
/usr/lib/x86_64-linux-gnu/libsgx_pce_logic.so: undefined reference to `sgx_get_metadata'
```

I'm not sure if the fix is to update _all_ of the `Depends:` to `>= 2.9`? Or perhaps just this one? Or maybe I'm misunderstanding these dependencies.

Thanks for your help.

**Comment by llly** [comment]
`libsgx-pce-logic` and `libsgx-qe3-logic` should depend on  `libsgx-urts` 2.9 and higher.  `sgx_get_metadata` is new interface introduced in libsgx-urts 2.9.
Thank you for finding the bug. We will fix it.
