### ISSUE TITLE
Compilation fails with error: ‘sgx_ql_qv_supplemental_t’ {aka ‘struct _sgx_ql_qv_supplemental_t’} has no member named ‘major_version’

### ISSUE THREAD

**Issue by OverOrion** [intel/SGXDataCenterAttestationPrimitives#280]
Hi!
I have tried compiling master and the latest release (DCAP_1.15) as well from source, but they failed with the following:

```bash
make[2]: Entering directory '/SGXDataCenterAttestationPrimitives/QuoteVerification/QvE'
Enclave/qve.cpp: In function ‘quote3_error_t qve_set_quote_supplemental_data(const intel::sgx::dcap::Quote&, const intel::sgx::dcap::CertificateChain*, const intel::sgx::dcap::parser::json::TcbInfo*, const _sgx_ql_qve_collateral_t*, const char**, time_t, time_t, time_t, uint8_t*)’:
Enclave/qve.cpp:981:36: error: ‘sgx_ql_qv_supplemental_t’ {aka ‘struct _sgx_ql_qv_supplemental_t’} has no member named ‘major_version’
  981 |             if (supplemental_data->major_version >= SUPPLEMENTAL_DATA_VERSION &&
      |                                    ^~~~~~~~~~~~~
Enclave/qve.cpp:982:36: error: ‘sgx_ql_qv_supplemental_t’ {aka ‘struct _sgx_ql_qv_supplemental_t’} has no member named ‘minor_version’
  982 |                 supplemental_data->minor_version >= SUPPLEMENTAL_V3_LATEST_MINOR_VERSION) {
      |                                    ^~~~~~~~~~~~~
Enclave/qve.cpp:988:53: error: ‘sgx_ql_qv_supplemental_t’ {aka ‘struct _sgx_ql_qv_supplemental_t’} has no member named ‘sa_list’
  988 |                     char *p_sa = supplemental_data->sa_list;
      |                                                     ^~~~~~~
Enclave/qve.cpp:994:39: error: ‘MAX_SA_LIST_SIZE’ was not declared in this scope
  994 |                         if (sa_size > MAX_SA_LIST_SIZE) {
      |                                       ^~~~~~~~~~~~~~~~
make[2]: *** [Makefile:138: Enclave/qve.o] Error 1
```
I ran git bisect as DCAP_1.14 compiled fine and it showed me 85cf8bd is the first commit that broke the compilation.

My environment:
- OS: Ubuntu 20.04
- CPU: i5-8365U
- compiler: g++-10 (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0

If there is something missing from my report, please let me know and I will share it.

**Comment by lzha101** [comment]
Perhaps you can check if you are using an old SGX SDK.  If yes, please install the latest SGX SDK and retry your build.

**Comment by mythi** [comment]
> Perhaps you can check if you are using an old SGX SDK. If yes, please install the latest SGX SDK and retry your build.

I'm seeing this too with DCAP 1.15 and SGX SDK 2.18 when building the `QuoteVerificationSample`

```
In file included from App/App.cpp:42:
/usr/include/sgx_dcap_quoteverify.h:307:5: error: ‘tee_supp_data_descriptor_t’ has not been declared
  307 |     tee_supp_data_descriptor_t *p_supp_data_descriptor);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
App/App.cpp: In function ‘int ecdsa_quote_verification(std::vector<unsigned char>, bool)’:
App/App.cpp:115:5: error: ‘tee_supp_data_descriptor_t’ was not declared in this scope
  115 |     tee_supp_data_descriptor_t supp_data;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
App/App.cpp:119:13: error: ‘supp_data’ was not declared in this scope
  119 |     memset(&supp_data, 0, sizeof(tee_supp_data_descriptor_t));
      |             ^~~~~~~~~
App/App.cpp:290:72: error: ‘sgx_ql_qv_supplemental_t’ {aka ‘struct _sgx_ql_qv_supplemental_t’} has no member named ‘major_version’
  290 |             printf("\tInfo: Supplemental data Major Version: %d\n", p->major_version);
      |                                                                        ^~~~~~~~~~~~~
App/App.cpp:291:72: error: ‘sgx_ql_qv_supplemental_t’ {aka ‘struct _sgx_ql_qv_supplemental_t’} has no member named ‘minor_version’
  291 |             printf("\tInfo: Supplemental data Minor Version: %d\n", p->minor_version);
      |                                                                        ^~~~~~~~~~~~~
App/App.cpp:295:45: error: ‘sgx_ql_qv_supplemental_t’ {aka ‘struct _sgx_ql_qv_supplemental_t’} has no member named ‘sa_list’
  295 |             if (p->version > 3 && strlen(p->sa_list) > 0) {
      |                                             ^~~~~~~
App/App.cpp:296:56: error: ‘sgx_ql_qv_supplemental_t’ {aka ‘struct _sgx_ql_qv_supplemental_t’} has no member named ‘sa_list’
  296 |                 printf("\tInfo: Advisory ID: %s\n", p->sa_list);
      |                                                        ^~~~~~~
App/App.cpp:404:72: error: ‘sgx_ql_qv_supplemental_t’ {aka ‘struct _sgx_ql_qv_supplemental_t’} has no member named ‘major_version’
  404 |             printf("\tInfo: Supplemental data Major Version: %d\n", p->major_version);
      |                                                                        ^~~~~~~~~~~~~
App/App.cpp:405:72: error: ‘sgx_ql_qv_supplemental_t’ {aka ‘struct _sgx_ql_qv_supplemental_t’} has no member named ‘minor_version’
  405 |             printf("\tInfo: Supplemental data Minor Version: %d\n", p->minor_version);
      |                                                                        ^~~~~~~~~~~~~
App/App.cpp:409:45: error: ‘sgx_ql_qv_supplemental_t’ {aka ‘struct _sgx_ql_qv_supplemental_t’} has no member named ‘sa_list’
  409 |             if (p->version > 3 && strlen(p->sa_list) > 0) {
      |                                             ^~~~~~~
App/App.cpp:410:56: error: ‘sgx_ql_qv_supplemental_t’ {aka ‘struct _sgx_ql_qv_supplemental_t’} has no member named ‘sa_list’
  410 |                 printf("\tInfo: Advisory ID: %s\n", p->sa_list);
      |                                                        ^~~~~~~
make[1]: *** [Makefile:223: App/App.o] Error 1
```

**Comment by llly** [comment]
`libsgx-dcap-quote-verify-dev` dev packages need to be updated too.
